name: Pipeline Java in EC2 - Prática Devops

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compilar por MAVEN
        run: mvn -B package --file pom.xml -DskipTests #usado para skipar as variaveis de ambiente

      - name: Deploy na EC2
        run: |
          echo "${{secrets.KEY_SSH_EC2}}" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i "private_key" ubuntu@ec2-34-225-230-10.compute-1.amazonaws.com "
            cd /home/ubuntu/POC && 
            git pull origin main &&
            mvn clean package -DskipTests &&
            ./executar.sh "
